image: docker

stages:
  - build
  - test
  - deploy

build_job_wpscan:
  stage: build
  script:
    - docker --version
    - docker build -t evild/alpine-wpscan:latest latest

test_job:
  stage: test
  script:
    - docker run --rm evild/alpine-wpscan --update

deploy_job:
  stage: deploy
  script:
    - git push --mirror https://$GITHUB_TOKEN@github.com/Evild67/docker-alpine-wpscan.git
